### ISSUE TITLE
Please add a `use lib` option

### ISSUE THREAD

**Issue by jaguart** [antononcube/Raku-UML-Translators#2]
Love the UML generation - thank you. Would appreciate the ability to include a library path.

When developing, my Classes are not fully installed, so I have to use the following

``raku -Ilib /home/armstrj/.rakubrew/versions/moar-2021.12/install/share/perl6/site/bin/to-uml-spec.raku --methods --attributes 'Jamd::PHP::Tiny'``

I would prefer to be able to:
``to-uml-spec.raku -Ilib --methods --attributes 'Jamd::PHP::Tiny'``

You could use --lib=lib or -Ilib etc.

Thanks again!

**Comment by antononcube** [comment]
Thank you for your interest and input! I will try to implement that feature this weekend.

**Comment by antononcube** [comment]
Implemented: the  `--I` argument can be used to specify an include directory.

For example:

```shell
to-uml-spec --I="./Raku-ML-TriesWithFrequencies/lib" "ML::TriesWithFrequencies"   
```

*Please give it a try! :)*
